name: LiteCookingMakerBridge
main: com.bonfire.litecookingmakerbridge.LiteCookingMakerBridgePlugin
version: 1.0.1
api-version: "1.21"
author: Bonfire
description: Add maker attribution and MMOCore exp bridge to LiteCooking rewards.
softdepend:
  - LiteCooking
